Sprint 1/step 2
JuniorPita/react-burger pull request #1
Opened 2023-05-30 17:17 UTC by JuniorPita

2023-05-30 17:35 UTC, JuniorPita commented
Для красоты кода ещё можно будет вынести массивы со статичными строками, которые используются в заголовках за пределы компонентов, а также сократить некоторые названия по типу element в el и так далее, но пока что оставил так для лучшей читаемости кода.

2023-05-30 19:02 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Реализовали закрытие по `ESC` и сделали отписку от слушателя событий
- Хорошая декомпозиция компонентов
- Хороший `сodestyle` - логичный и понятный код

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- Рапишите тип ингредиента в `propTypes` и используйте везде где он принимается в пропсах
- у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-30 19:02 UTC, andryxxa93 commented on src/components/app/app.jsx
> +      return await fetch(UrlApiAdress)
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-05-30 19:02 UTC, andryxxa93 commented on src/components/app/app.jsx
> +    const getInformation = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-05-30 19:02 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        .catch((error) => new Error(`Уловил ошибку: ${error}`));
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к фзш api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-05-30 19:02 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +BurgerConstructor.propTypes = {
**Необходимо исправить**
Сейчас получается, что под `elements ` может прийти массив любого содержания, но это не так. Необходимо полностью расписать тип ингредиента со всеми его полями (чтобы не дублировать код - сделайте это в отдельном файле) и использовать во всех подобных местах. Вам помогут в этом функции propTypes `arrayOf` и `shape`.

2023-05-30 19:02 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          {elements.map((object) => {
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2023-05-30 19:02 UTC, andryxxa93 commented on src/utils/data.js
> +export const data = [
**Можно лучше**
Моковые данные уже можно удалить

2023-05-30 19:03 UTC, andryxxa93 commented
> Для красоты кода ещё можно будет вынести массивы и объекты со статичными строками, которые используются в заголовках за пределы компонентов, а также сократить некоторые названия по типу element в el и так далее, но пока что оставил так для лучшей читаемости кода.

сокращать названия `element` на `el` - не нужно, это особо ничего не даст, а читаемость кода и его расширение упадёт

2023-06-01 05:54 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-01 05:54 UTC, andryxxa93 commented on src/utils/check-response.js
> +  return false;
**МОжно лучше**
Рекомендую возвращать объект ошибки как в примере, что я вам дал, это вам пригодится в будущих спринтах

2023-06-01 08:03 UTC, merged